FROM golang:1.17 as builder

ARG GOOS=linux
ARG GOARCH=amd64

WORKDIR "/code"
ADD . "/code"
RUN make BINARY=spring-config-decryptor os.build
RUN cp /code/spring-config-decryptor /spring-config-decryptor